name: Get GZA OTA buckets

on:
  workflow_dispatch:
    inputs:
      cloud_env:
        description: Cloud Environment
        required: true
        type: choice
        default: dev1
        options:
        - dev1
        - qa1
      model:
        description: Product Name
        required: true
        type: string
        default: 'PR2100 PR4100 EX2100 EX4100 DL2100 DL4100 EX2Ultra Mirror Glacier Mirrorman'
      special_bucket:
        description: Special bucket
        required: true
        type: boolean
        default: true
jobs:
    get_gza_ota_bucket:
      name: Get GZA buckets - ${{ inputs.cloud_env }} - special_bucket:${{ inputs.special_bucket }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v3
        - name: Change file permission
          run: |
            chmod 755 ./start.sh
            chmod 755 ./app/run.sh
        - name: Set parameter
          id: set_param
          run: |
            if [ ${{ inputs.special_bucket }} == true ]; then
              echo "special_bucket=--special_bucket" >> $GITHUB_ENV
            else
              echo "special_bucket=" >> $GITHUB_ENV
            fi
        - name: Send script command
          run: ./start.sh jenkins_scripts/update_gza_ota_bucket.py -env ${{ inputs.cloud_env }} -m ${{ inputs.model }} ${{ env.special_bucket }} --method get
