name: GZA BAT

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Cloud environment'
        required: true
        type: choice
        options:
          - dev1
          - qa1
          - prod
      model:
        description: 'Product Name'
        required: true
        type: choice
        options:
          - PR2100
          - PR4100
          - EX2100
          - EX4100
          - DL2100
          - DL4100
          - EX2Ultra
          - Mirror
          - Glacier
          - Mirrorman
      firmware_version:
        description: "Test firmware version"
        required: true
        type: string
  workflow_call:
    inputs:
      environment:
        description: 'Cloud environment'
        required: true
        type: string
        default: 'dev1'
      model:
        description: 'Product Name'
        required: true
        type: string
        default: 'PR2100'
      firmware_version:
        description: "Test firmware version"
        required: true
        type: string
jobs:
  execute_gza_bat:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Change file permission
        run: |
          chmod 755 ./start.sh
          chmod 755 ./app/run.sh
      - name: Check the Bash version
        run: echo $BASH_VERSION
      - name: Get device IP address
        run: |
          #!/bin/bash
          declare -A ip_address
          ip_address["PR2100"]="10.92.224.48"
          ip_address["PR4100"]="10.92.224.49"
          ip_address["EX2100"]="10.92.224.50"
          ip_address["EX4100"]="10.92.224.51"
          ip_address["DL2100"]="10.92.224.52"
          ip_address["DL4100"]="10.92.224.53"
          ip_address["EX2Ultra"]="10.92.224.54"
          ip_address["Mirror"]="10.92.224.55"
          ip_address["Glacier"]="10.92.224.56"
          ip_address["Mirrorman"]="10.92.224.57"
          echo "device_ip_address=${ip_address['${{ inputs.model }}']}" >> $GITHUB_ENV
      - name: Send the script command
        run: |
          #!/bin/bash
          SCRIPT_ARGV=" -env ${{ inputs.environment }} -model ${{ inputs.model }}"
          SCRIPT_ARGV+=" -ip ${{ env.device_ip_address }} -fw ${{ inputs.firmware_version }}"
          SCRIPT_ARGV+=" -u wdcautotw+qawdc.gza.${{ inputs.model }}@gmail.com -p Password1234#"
          SCRIPT_ARGV+=" --stream_log_level DEBUG --dry_run --disable_upload_popcorn_report --disable_upload_logs"
          echo $SCRIPT_ARGV
          # ./start.sh godzilla_scripts/integration_tests/platform_bat.py $SCRIPT_ARGV