name: GZA BAT

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test environment'
        required: true
        type: choice
        options:
          - dev1
          - qa1
          - prod
      model:
        description: 'Product Name'
        required: true
        type: choice
        options:
          - PR2100
          - PR4100
          - EX2100
          - EX4100
          - DL2100
          - DL4100
          - EX2Ultra
          - Mirror
          - Glacier
          - Mirrorman
  workflow_call:
    inputs:
      environment:
        description: 'Test environment'
        required: true
        type: string
        default: 'dev1'
      model:
        description: 'Product Name'
        required: true
        type: string
        default: 'PR2100'
jobs:
  execute_gza_bat:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Change file permission
        run: |
          chmod 755 ./start.sh
          chmod 755 ./app/run.sh
      - name: Check the Bash version
        run: echo $BASH_VERSION
      - name: Get device IP address
        run: |
          #!/bin/bash
          declare -A ip_address
          ip_address["PR2100"]="10.92.224.48"
          ip_address["PR4100"]=""
          ip_address["EX2100"]=""
          ip_address["EX4100"]=""
          ip_address["DL2100"]=""
          ip_address["DL4100"]=""
          ip_address["EX2Ultra"]=""
          ip_address["Mirror"]=""
          ip_address["Glacier"]=""
          ip_address["Mirrorman"]=""
          echo "device_ip_address=${ip_address['${{ inputs.model }}']}" >> $GITHUB_ENV
          echo "Device IP address: ${{ env.device_ip_address }}"
      - name: Send the script command
        run: |
          #!/bin/bash
          SCRIPT_ARGV=" -env ${{ inputs.cloud_env }} -model ${{ inputs.model }} -ip ${{ env.device_ip_address }}"
          SCRIPT_ARGV+=" --stream_log_level DEBUG --dry_run --disable_upload_popcorn_report --disable_upload_logs"
          echo "SCRIPT_ARGV=$SCRIPT_ARGV"
          # ./start.sh godzilla_scripts/integration_tests/platform_bat.py $SCRIPT_ARGV