name: Test downstream jobs - destination

on:
  workflow_run:
    workflows: ["Get GZA OTA buckets"]
    types:
      - completed

jobs:
  test_downstream_destination:
    runs-on: ubuntu-latest
    steps:
      - name: Send script command
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            echo "Up stream job success"
          else
            echo "Up stream job failed"
          fi
          echo 'Simple workflow to test downstream jobs. This is the destination.'
