name: Trigger Other Workflow
on:
  workflow_dispatch:
    inputs:
      workflow-name:
        description: 'Name of the workflow to trigger'
        required: true
        default: 'get_gza_ota_buckets'  # Default name of the workflow to trigger

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Other Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: ${{ github.event.inputs.workflow-name }}
          cloud_env: 'qa1'
          model: 'PR4100'
          special_bucket: 'true'
